--CREATE SCHEMA schema_wallet
--    AUTHORIZATION postgres;

--CREATE SEQUENCE IF NOT EXISTS schema_wallet.HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE  WALLET (
id NUMBER(38, 0) NOT NULL,
user_id VARCHAR2(50) NOT NULL,
version NUMBER(11) DEFAULT 0 NOT NULL,
balance DECIMAL(21, 2) DEFAULT 0 NOT NULL,
currency_type	VARCHAR2(50) NOT NULL,
last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
last_updated_by VARCHAR2(50) DEFAULT 'admin',
CONSTRAINT PK_WALLET PRIMARY KEY (id));




CREATE TABLE TRANSACTION
(
id NUMBER(38, 0) NOT NULL,
global_id VARCHAR2(50) NOT NULL,
type VARCHAR2(50) NOT NULL,
amount DECIMAL(21, 2) DEFAULT 0 NOT NULL,
wallet_id NUMBER(38, 0) REFERENCES wallet(id),
currency_type VARCHAR2(50) NOT NULL,
description VARCHAR2(250),
last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
last_updated_by VARCHAR2(50) DEFAULT 'admin'
);